### ISSUE TITLE
'H' must be numeric. 'data' converted! 'Amount' must be numeric. 'data' converted! Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok,  :    0 (non-NA) cases

### ISSUE THREAD

**Issue by DBGordon1** [OskarHansson/strvalidator#20]
Oskar Hansson,

I am a graduate student at Boston University and I am conducting a comparative analysis of different AT methods. Specifically I am comparing AT6 with a different cost based approach. I built my 'sample data set', 'reference data set' and 'amount data set' and imported them on to the most current version of STR validator per the instructions you provided. However, whenever I try to calculate AT 6, I get the following error message.

'H' must be numeric. 'data' converted!
'Amount' must be numeric. 'data' converted!
Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok,  : 
  0 (non-NA) cases

I am not sure what is causing this. When I viewed my amount data set import on the GUI interface the values appeared to be numeric. I have attached all three data sets. Any advice would be helpful. Thank you.

Dan
[ref data set A.csv](https://github.com/OskarHansson/strvalidator/files/7797886/ref.data.set.A.csv)
[Amount.csv](https://github.com/OskarHansson/strvalidator/files/7797887/Amount.csv)
[A Dataset.csv](https://github.com/OskarHansson/strvalidator/files/7797888/A.Dataset.csv)

**Comment by OskarHansson** [comment]
Hi Dan,

Thanks for reaching out with your problem and providing files for testing. Because of rare erroneous cases with autodetection of input data type when I built the import function, all data are currently imported as text, then some known standard columns are converted to numeric. This may be changed in the future as the `fread` function may now support a parameter for number of lines for autodetection https://github.com/OskarHansson/strvalidator/blob/0b91975838ff8cad8d18c9ab93fb11d4dc23d0d0/R/import.r#L190

Anyway, the first two lines just state that the text data was converted to numeric before running the function.

For the third line show an error related to `lm.wfit`, a function in the [stat package](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lmfit.html). By searching you will get a clue to the cause which most likely is no input data (e.g. https://stackoverflow.com/questions/43677853/error-in-lm-fitx-y-offset-offset-singular-ok-0-non-na-cases-with-boxcox/43678700). 

Check the data
Looking at the imported data I noticed that the data is sorted by marker, not by sample name and then by marker. I have never worked with data sorted that way, and it may lead to unexpected results.

Make sure the sample matching works
When clicking the "Check subsetting" button, there is no match to the reference samples, which probably leads to an empty input dataset to the lm-function. I am not sure why, and will not dig deeper right now, but it seems like the parenthesis in the sample names might be the cause. 

You can "remove" the parenthesis part of the sample names by using the Tools/Columns function:

1. Select the dataset.
2. Select "Sample.Name" as column 1 (leave column 2 empty).
3. Leave "Sample.Name" as column for new values.
4. Select "substr" as action.
5. Type 1 as start position and 3 as stop position.
6. Click Execute.
7. Repeat for all datasets.
8. Use the new datasets as input.

For me, this gives no error messages and I can produce a plot.

NB! The console output (below) give two lines for each sample, so there may be some more data cleaning required.

Try again after checking the above points. Let me know how it works.

```
Processed data to be used in regression:
   Sample.Name    TPH Denominator          H Peaks Expected Proportion Amount
1          1A1 254943          44 5794.15909    42       42          1    800
2          1A1 254943          NA    0.00000    42       NA          0    800
3          1A2 127360          44 2894.54545    42       42          1    800
4          1A2 127360          NA    0.00000    42       NA          0    800
5          1A3 217277          44 4938.11364    42       42          1    800
6          1A3 217277          NA    0.00000    42       NA          0    800
7          1A4 181635          44 4128.06818    42       42          1    800
8          1A4 181635          NA    0.00000    42       NA          0    800
9          1A5 120380          44 2735.90909    42       42          1    800
10         1A5 120380          NA    0.00000    42       NA          0    800
11         2A1 105751          44 2403.43182    42       42          1    400
12         2A1 105751          NA    0.00000    42       NA          0    400
13         2A2 119357          44 2712.65909    42       42          1    400
14         2A2 119357          NA    0.00000    42       NA          0    400
15         2A3    545          12   45.41667     8        8          1    400
16         2A3    545          NA    0.00000     8       NA          0    400
17         2A4 167257          44 3801.29545    42       42          1    400
18         2A4 167257          NA    0.00000    42       NA          0    400
19         2A5  47842          44 1087.31818    42       42          1    400
20         2A5  47842          NA    0.00000    42       NA          0    400
21         3A1   1357          28   48.46429    19       19          1    200
22         3A1   1357          NA    0.00000    19       NA          0    200
23         3A2  80584          44 1831.45455    42       42          1    200
24         3A2  80584          NA    0.00000    42       NA          0    200
25         3A3  56065          44 1274.20455    42       42          1    200
26         3A3  56065          NA    0.00000    42       NA          0    200
27         3A4  33453          44  760.29545    42       42          1    200
28         3A4  33453          NA    0.00000    42       NA          0    200
29         3A5  18470          44  419.77273    41       41          1    200
30         3A5  18470          NA    0.00000    41       NA          0    200
31         4A1  23615          44  536.70455    41       41          1    100
32         4A1  23615          NA    0.00000    41       NA          0    100
33         4A2  24892          44  565.72727    40       40          1    100
34         4A2  24892          NA    0.00000    40       NA          0    100
35         4A3  12223          44  277.79545    40       40          1    100
36         4A3  12223          NA    0.00000    40       NA          0    100
37         4A4   7874          42  187.47619    35       35          1    100
38         4A4   7874          NA    0.00000    35       NA          0    100
39         4A5  26227          44  596.06818    41       41          1    100
40         4A5  26227          NA    0.00000    41       NA          0    100
41         5A1   3609          NA    0.00000    21       NA          0     50
42         5A1   3609          32  112.78125    21       21          1     50
43         5A2  30584          44  695.09091    41       41          1     50
44         5A2  30584          NA    0.00000    41       NA          0     50
45         5A3  25212          44  573.00000    42       42          1     50
46         5A3  25212          NA    0.00000    42       NA          0     50
47         5A4   2109          NA    0.00000     6       NA          0     50
48         5A4   2109           8  263.62500     6        6          1     50
49         5A5  25130          44  571.13636    41       41          1     50
50         5A5  25130          NA    0.00000    41       NA          0     50
```

**Comment by DBGordon1** [comment]
Oskar Hansson,

Thank you the reply. The formatting change you recommended seems to have fixed the problem and I am able to generate an AT Plot. I did have one more question though. The literature I am reading on the AT 6 method, states that known homozygous allelic peaks should be divided by two before being used to determine the average peak height by concentration at each DNA input. Does the STR Validator software perform this step for me or will I need to divide my homozygous peak height RFUs by 2 prior to importing the genotype table data to STR Validator? Please respond at your earliest convenience thank you.

Dan

**Comment by OskarHansson** [comment]
Hi Dan,

As you can see from the source code for the calculateAT6 function, it uses the average peak height as input, which is calculated by the calculateHeight function: https://github.com/OskarHansson/strvalidator/blob/0b91975838ff8cad8d18c9ab93fb11d4dc23d0d0/R/calculateAT6.r#L187

According to the documentation (type  `?calculateHeight` in the console) H is calculated according to the formula: H = sum(peak heights)/(n[het] + 2n[hom], where: n[het] = number of observed heterozygous alleles and n[hom] = number of observed homozygous alleles (also see the referenced paper). So you don't need to divide by two:
https://github.com/OskarHansson/strvalidator/blob/0b91975838ff8cad8d18c9ab93fb11d4dc23d0d0/R/calculateHeight.r#L255
https://github.com/OskarHansson/strvalidator/blob/0b91975838ff8cad8d18c9ab93fb11d4dc23d0d0/R/calculateHeight.r#L263
https://github.com/OskarHansson/strvalidator/blob/0b91975838ff8cad8d18c9ab93fb11d4dc23d0d0/R/calculateHeight.r#L273

The function only considers observed expected alleles i.e. if you have drop-outs, the average peak height is calculated with the observed peak heights only, disregarding dropped out alleles. Consequently, the average peak height may be overestimated when there are dropouts.
