### ISSUE TITLE
Issue when attempting to calculate drop-out risk

### ISSUE THREAD

**Issue by filippobarni** [OskarHansson/strvalidator#25]
Dear Oskar,

please find below an error message I got when attempting to model drop-out risk:

Error in !is.na(predictionDf) && !is.null(predictionDf) : 
  'length = 14116' in coercion to 'logical(1)'

Do you have any suggestion to overcome this issue? It you think it could help I can forward to you by e-mail the dataset (and reference) used for calculation drop-out and stochastic threshold. Moreover: do you have an updated version of the manual concerning the drop-out and stochastic threshold calculations given that they are quite different with respect to the first version of the software?

Thank you for your support.

Filippo Barni
(Carabinieri RIS Rome)

**Comment by OskarHansson** [comment]
The bug was fixed in the attached files 16th of august, by private mail.  

[strvalidator_2.4.1.9002.tar.gz](https://github.com/user-attachments/files/16795770/strvalidator_2.4.1.9002.tar.gz)
[strvalidator_2.4.1.9002.zip](https://github.com/user-attachments/files/16795772/strvalidator_2.4.1.9002.zip)
